
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "ServidorProyectoMP12"
  config.vm.define "servidor"
  config.vm.network :forwarded_port, host: 4000, guest: 80
  config.vm.network :forwarded_port, host: 4001, guest: 3306
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "html/", "/var/www/html"
  config.vm.provider "virtualbox" do |vb|
vb.name = "serverMp12"
vb.memory = "1024"
vb.cpus = 1
   end
  config.vm.provision "shell", path: "script.sh"
end